//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfShowCase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GolfVersion
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "Version Name")]
        [StringLength(60, MinimumLength = 5)]
        [RegularExpression(@"(Golf).*", ErrorMessage = "The Version Name Must begin with the word Golf")]
        public string VersionName { get; set; } //the only one that i think i really required

        public string Image { get; set; }

        [Display(Name = "Year of Release")]
        [Range(1920, 2018)]
        public string StartProduction { get; set; }

        [Display(Name = "End of Production")]
        [Range(1920, 2025)]
        public string EndProduction { get; set; }

        [Display(Name = "Units Produced")]
        [Range(1, 20000000)]
        public Nullable<int> NumberMade { get; set; }

        [Display(Name = "Launch Price £")]
        [DataType(DataType.Currency)]
        [Range(1, 500000)]
        public Nullable<decimal> StartingPrice { get; set; }

        [Display(Name = "Fuel Type")]
        public string FuelType { get; set; }

        [Display(Name = "Engin Power (hp)")]
        [Range(4, 700)]
        public Nullable<int> EnginSize { get; set; }

        [Display(Name = "Top Speed (mph)")]
        [Range(40, 500)]
        public Nullable<int> TopSpeed { get; set; }

        [Display(Name = "Acceleration Seconds to 0-62mph")]
        [Range(1, 50)]
        public Nullable<decimal> Accelleration { get; set; }

        [Display(Name = "More Info")]
        public string Description { get; set; }
    }
}
